### ISSUE TITLE
Executing command "azd pipeline config" failed.

### ISSUE THREAD

**Issue by Menghua1** [fangjian0423/todo-java-postgresql-aca-terraform#1]
**Describe the issue:**
When executing command `azd pipeline config`, an error is reported in the github pipeline that azd is not logged in.
The detailed error is as follows:
![image](https://user-images.githubusercontent.com/111940661/219560598-c811ae9e-9705-4097-bb50-b6aa73e7bc95.png)

**Repro Steps:**
1.Execute command `azd up --template https://github.com/fangjian0423/todo-java-postgresql-aca-terraform -l "eastus"` .

2.Run: `azd pipeline config`.

3.Click on the link that is printed to open the actions page.

**Environment:**

- OS: windows .
- Template: https://github.com/fangjian0423/todo-java-postgresql-aca-terraform
- Branch: main.
- Azd version: azd version 0.6.0-beta.3-daily.2193634 (commit e7541b22738f36091793bcec299aa6595e742937)

**Expected behavior:**
Action logs can pass successfully.

@fangjian0423 for notification.

**Comment by fangjian0423** [comment]
Please try again, the issue has been fixed.

**Comment by Menghua1** [comment]
@fangjian0423 The above issue has been fixed, but now we have encountered a new issue when executing command `azd pipeline config`. Please help to check and resolve it.
The detailed error is as follows:
![image](https://user-images.githubusercontent.com/111940661/220812998-0759602b-12ec-4ce2-a8ce-c36f622ce658.png)

**Comment by fangjian0423** [comment]
@Menghua1 

Terraform template deploy to Azure Container Apps is different with others, please add extra 2 steps:

1. follow https://aka.ms/azure-dev/terraform update provider.tf and add provider.conf.json in `infra/api` directory.
2. follow https://aka.ms/azure-dev/terraform update provider.tf and add provider.conf.json in `infra/web` directory.

Remember don't use the same key in 3 provider.conf.json files.

**Comment by fangjian0423** [comment]
I have added relevant hints in README.

**Comment by Menghua1** [comment]
@fangjian0423 According to the two extra steps you provided, after retesting, this issue has been fixed. We will close this issue.
